#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Change this to use a non-default directory for Vector data storage:
# data_dir = "/var/lib/vector"

# Random Syslog-formatted logs
[sources.dummy_logs]
type = "demo_logs"
format = "syslog"
interval = 1

# Parse Syslog logs
# See the Vector Remap Language reference for more info: https://vrl.dev
[transforms.parse_logs]
type = "remap"
inputs = ["dummy_logs"]
source = '''
. = parse_syslog!(string!(.message))
del(.timestamp)
del(.message)
'''
[transforms.parse_logs_filter]
type      = "filter"
inputs    = [ "parse_logs" ]
condition = '.severity == "emerg"'

[transforms.parse_logs_metric]
type   = "log_to_metric"
inputs = [ "parse_logs_filter" ]

  [[transforms.parse_logs_metric.metrics]]
  type      = "counter"
  field     = "severity"
  name      = "sev_total"
  namespace = "veera_log"

[sinks.parse_logs_export_metric]
type              = "prometheus_exporter"
inputs            = [ "parse_logs_metric" ]
address           = "0.0.0.0:9598"
default_namespace = "veera_log"



# Print parsed logs to stdout
#[sinks.print]
#type = "console"
#inputs = ["parse_logs_filter"]
#encoding.codec = "json"
# Vector's GraphQL API (disabled by default)
# Uncomment to try it out with the `vector top` command or
# in your browser at http://localhost:8686
[api]
enabled = true
address = "127.0.0.1:8686"
